## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [1]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [2]:
# Q1-1
import pandas as pd
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}
pd.DataFrame(data,columns=["name","job","family_size","num_cars"])

name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1

In [3]:
# Q1-2
df = pd.DataFrame(data,columns=["name","job","family_size","num_cars"])
df[(df["job"]=="psychologist") | (df["job"]=="teacher")]
df[(df["num_cars"]>df["family_size"])]

name           job  family_size  num_cars
5  Lisa  psychologist            3         4

In [4]:
# Q1-3
df[(df["family_size"]<=2)&(df["num_cars"]>=1)]

name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1

In [5]:
# Q1-4
print(len(df["job"].unique()))

4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [48]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [49]:
# Type your solution here
frame = {'fruit':fruit,'weight':weights}
f = pd.DataFrame(frame)
apple = f[f["fruit"]=="apple"]
num_apple = len(apple)
if num_apple > 0:
  sum_apple = apple.sum(axis=0)
  sum_apple_array = sum_apple.array
  mean_apple = sum_apple_array[1] / num_apple
else:
  mean_apple = 0
print("Mean weight of apple: " + str(mean_apple))
banana = f[f["fruit"]=="banana"]
num_banana = len(banana)
if num_banana > 0:
  sum_banana = banana.sum(axis=0)
  sum_banana_array = sum_banana.array
  mean_banana = sum_banana_array[1] / num_banana
else:
  mean_banana = 0
print("Mean weight of banana: " + str(mean_banana))
carrot = f[f["fruit"]=="carrot"]
num_carrot = len(carrot)
if num_carrot > 0:
  sum_carrot = carrot.sum(axis=0)
  sum_carrot_array = sum_carrot.array
  mean_carrot = sum_carrot_array[1] / num_carrot
else:
  mean_carrot = 0
print("Mean weight of carrot: " + str(mean_carrot))


Mean weight of apple: 9.5
Mean weight of banana: 6.5
Mean weight of carrot: 3.8333333333333335


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [50]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [51]:
# Q3-1
indices = np.argsort(course_name)
print(indices)

[1 3 0 2 4]


In [52]:
# Q3-2
check = np.char.startswith(course_name,"P")
print(check)

[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [53]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [54]:
# Q4-1
print(student_id)
print(student_id[::-1])

[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]


In [55]:
# Q4-2
np.sort(student_id)
print(student_id[-3:])

[1682 5241 4532]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [56]:
# Type your solution here
import numpy as np
numbers = np.arange(1,100)
multiples = numbers[(numbers % 3 == 0) | (numbers % 5 ==0)]
print(multiples.sum())

2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [78]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [75]:
# Q6-1
arr = np.arange(12).reshape(3,4)
arr[:,[1,2]] = arr[:,[2,1]]
print(arr)

[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]


In [77]:
# Q6-2
arr = np.arange(12).reshape(3,4)
arr[[0,1],:] = arr[[1,0],:]
print(arr)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
